services:
  - type: web
    name: portfolio-app
    env: node
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "cross-env NODE_ENV=production node dist/index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_USER
        sync: false  
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_SECURE
        sync: false
      - key: EMAIL_FROM
        sync: false
    healthCheckPath: /